import {classNames} from "@/utils/classNames";
import Head from 'next/head'
import { Noto_Sans_KR, Noto_Sans } from 'next/font/google'

const notoSansKR = Noto_Sans_KR({
  weight: ['400'],
  display: 'swap',
  variable: '--font-notoSansKR',
  subsets: ['latin'],
})

const notoSans = Noto_Sans({
  weight: ['400'],
  display: 'swap',
  variable: '--font-notoSans',
  subsets: ['latin'],
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={classNames(notoSansKR.variable, notoSans.variable, 'font-sans')}>
        <h1 className="text-3xl font-bold underline">
          한글
        </h1>
      </main>
    </>
  )
}
