import { classNames } from '@/utils/classNames'
import { Noto_Sans, Noto_Sans_KR } from 'next/font/google'
import Head from 'next/head'
import { FormEventHandler, useState } from 'react'

const notoSansKR = Noto_Sans_KR({
  weight: ['400'],
  display: 'swap',
  variable: '--font-notoSansKR',
  subsets: ['latin'],
})

const notoSans = Noto_Sans({
  weight: ['400'],
  display: 'swap',
  variable: '--font-notoSans',
  subsets: ['latin'],
})

const Form = () => {
  const [isShowLink, setShowLink] = useState(false)
  const onSubmit: FormEventHandler<HTMLFormElement> = async (e) => {
    e.preventDefault()
    const body = new FormData(e.target as HTMLFormElement)

    try {
      await fetch('/api/upload', {
        method: 'POST',
        body,
      })
      setShowLink(true)
    } catch (e) {
      alert(e)
    }
  }

  return (
    <>
      <form onSubmit={onSubmit}>
        <label>
          <input type="file" name="token"></input>
          <button type="submit">전송</button>
        </label>
      </form>
      <a href="/themes/css/global.css" target="_blank" hidden={!isShowLink}>
        css 다운로드
      </a>
    </>
  )
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={classNames(
          notoSansKR.variable,
          notoSans.variable,
          'font-sans'
        )}
      >
        <Form />
      </main>
    </>
  )
}
